### ISSUE TITLE
Issues with shiny perl (using conda-forge perl on Linux)

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#384]
The goal of shiny perl is to rebuild the perl pieces / modules using conda > 4.8 .
It would also be preferred to use a provided perl instead of compiling perl directly.

On Linux (fido CentOS 7) when trying to build the skare3-static package perl-core-deps using the perl provided in the  'defaults' channel, there is what looks to be a problem in linking:
```
Configuring File-Map-0.66
Running Build.PL
/fido.real/reboot/builds/perl-core-deps_1593204029948/_h_env_placehold_placehold_placehold_placehold_placehold_placehol
d_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
ld_placehold_plac/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cann
ot find crti.o: No such file or directory
collect2: error: ld returned 1 exit status
```

If I look at the output of perl -V for the linux defaults 5.26.2 package h14c3975_0 that should be in use in that environment, the paths of compiler and linker don't look great as /tmp/build does not exist on the building machine:

```  
Compiler:
    cc='/tmp/build/80754af9/perl_1527832170752/_build_env/bin/x86_64-conda_cos6-linux-gnu-gcc'
Linker and Libraries:
    ld='/tmp/build/80754af9/perl_1527832170752/_build_env/bin/x86_64-conda_cos6-linux-gnu-gcc'
```

Course they don't look much like the path from the linker error above either so that's confusing (maybe if ld is set to something that doesn't make sense it defaults to try an ld a search path?) If I use the perl 5.26.2 from conda it has somewhat more sane-looking paths consider the conda debug environment:

```
  Compiler:
    cc='/fido.real/conda_4.8/envs/builder/conda-bld/debug_1593205696418/_h_env/bin/..//bin/x86_64-conda_cos6-linux-gnu-
gcc'  
Linker and Libraries:
    ld='/fido.real/conda_4.8/envs/builder/conda-bld/debug_1593205696418/_h_env/bin/..//bin/x86_64-conda_cos6-linux-gnu-
gcc'
```
From previous experience, I know a bunch of the perl package building relies on functional compilers described in the perl Config so the conda-forge perl seems a better place to start.  I don't have any great "test" packages to build with perl using its referenced compilers except for all of the packages in perl-core-deps, so I've been using success there as a sign that the combination is somewhat reasonable.

The plan is to continue building/testing with a mixed environment with just this perl package from conda-forge but everything else from defaults/shiny.

**Comment by javierggt** [comment]
I guess this is solved, since we have ska3-perl in shiny.

**Comment by jeanconn** [comment]
No.  This is still an issue... I just had to get a specific version of the package from conda-forge to *make* it work in shiny.  Not sure about the best place to remind ourselves of the issue when/if we try to update core packages.

**Comment by javierggt** [comment]
I reopened the issue because of your latest comment.

However, I'm not sure that open issues is the place to document things. One way would be to use tags. Then you can look at all issues with a given set of tags, including closed issues. For example: "perl" "conda-forge" "getting things to work" (whatever).

Then, each issue should have a limited lifetime (like branches). Whatever it is, there is usually some kind of resolution. After it is resolved, the issue is closed. This issue was resolved when you found a version in conda-forge that made ska3-perl work.

**Comment by jeanconn** [comment]
Since we've moved to conda-forge in general, I think this is no longer an issue.
